package com.gsccs.cmcc.work.dao;

import com.gsccs.cmcc.work.model.Plan;
import com.gsccs.cmcc.work.model.PlanExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PlanMapper {

	int countByExample(PlanExample example);

	int deleteByExample(PlanExample example);

	int deleteByPrimaryKey(String id);

	int insert(Plan record);

	int insertSelective(Plan record);

	List<Plan> selectByExample(PlanExample example);
	List<Plan> selectPageByExample(PlanExample example);

	Plan selectByPrimaryKey(String id);

	int updateByExampleSelective(@Param("record") Plan record,
			@Param("example") PlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sqfw_work_plan
	 * 
	 * @mbggenerated Tue Oct 20 11:57:22 CST 2015
	 */
	int updateByExample(@Param("record") Plan record,
			@Param("example") PlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sqfw_work_plan
	 * 
	 * @mbggenerated Tue Oct 20 11:57:22 CST 2015
	 */
	int updateByPrimaryKeySelective(Plan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sqfw_work_plan
	 * 
	 * @mbggenerated Tue Oct 20 11:57:22 CST 2015
	 */
	int updateByPrimaryKey(Plan record);
}